/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    ConfirmDialog: typeof import('./src/components/ConfirmDialog.vue')['default']
    CreateUserDialog: typeof import('./src/components/CreateUserDialog.vue')['default']
    EditUserDialog: typeof import('./src/components/EditUserDialog.vue')['default']
    FileList: typeof import('./src/components/FileList.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    RenameDialog: typeof import('./src/components/RenameDialog.vue')['default']
    ResetPasswordDialog: typeof import('./src/components/ResetPasswordDialog.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UploadDialog: typeof import('./src/components/UploadDialog.vue')['default']
  }
}
